spring:
  redis:
    host: 101.200.123.114
    port: 6379
    password: redis_repay
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 100
        max-wait: 15000ms
        min-idle: 50